---
name: "ECOLE Project (Educational Community Living Environment)"
description: |
  ECOLE (Educational Community Living Environment) is a model of urban sustainable living and a physical hub for the McGill and Montreal sustainability communities. Our mandate is to bring together McGill students, faculty and staff and Montreal community members in the pursuit of sustainable living by means of applied student research, alternative education, and community building. ECOLE is an ongoing experiment that strives to be a model of urban sustainable living. ECOLE has ten facilitators that live in our physical building (3559 Rue University) that host many types of events and workshops for the greater McGill / Milton Parc communities.
status: active
social_media:
  facebook: "https://www.facebook.com/ECOLEProject/"
  instagram: "https://www.instagram.com/ecoleproject/"
  other:
    - "https://www.linkedin.com/company/ecoleproject/about/"
website: "https://www.ecoleproject.com/"
contact_info: |
  ecoleproject@gmail.com
categories:
  community support:
    - Sustainability
    - Social Activism
