---
name: "ESG (Environmental, Social, Governance) McGill"
description: |
  Open to all students, ESG (Environmental, Social, Governance) McGill is focused on improving members’ financial literacy skills while exploring how market-based solutions can help mitigate social and climate issues. We are an environmentally oriented business club seeking diverse points of view from all perspectives. Through educational reporting, networking opportunities, and speaker events, our club seeks to promote the emerging sphere of ESG on campus. We're interested in your financial future, and the future of the planet!
status: active
social_media:
  facebook: "https://www.facebook.com/esgmcgill"
  instagram: "https://www.instagram.com/esg_mcgill/"
  other:
    - "https://www.youtube.com/channel/UCB-DMNT-BNERpYfPlcl_HIg"
website: "http://esg.ssmu.ca/"
contact_info: |
  esg@ssmu.ca
categories:
  community support:
    - Social Activism
    - Sustainability
  career:
    - Networking
