---
name: "MESS – McGill Environment Students’ Society"
description: |
  The McGill Environment Students' Society logo Environment Students’ Society (MESS) represents undergraduate and diploma Environment students at McGill University.
status: active
social_media:
  facebook: "https://www.facebook.com/pages/Mcgill-Environment-Students-Society/484032635041257"
  other:
website: "https://www.mcgill.ca/environment/current-students/mess"
contact_info: |
  mcgill.environment@gmail.com
categories:
  career:
    - Professional Development
    - Networking
  faculty specific:
    - Arts
  culture:
    - Student Society
