name: CommitLint

on: [push, pull_request]

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # fetch full history to access all commits
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16
            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version
                  npx commitlint --version
            - name: Install commitlint
              run: |
                  npm install conventional-changelog-conventionalcommits
                  npm install commitlint@latest

            - name: Validate all commits in a push with commitlint
              if: github.event_name == 'push'
              run: npx commitlint --from ${GITHUB_SHA}~$(git rev-list --count ${GITHUB_SHA}) --to ${GITHUB_SHA} --verbose

            - name: Validate PR commits with commitlint
              if: github.event_name == 'pull_request'
              run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
