name: CommitLint

on:
    push:
        branches-ignore: [master]
    pull_request:
        branches-ignore: [master]

jobs:
    commitlint:
        name: CommitLint Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0 # fetch full history to access all commits
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"
            - name: Print versions
              run: |
                  git --version
                  node --version
                  npm --version
                  npx commitlint --version
            - name: Install dependencies
              run: npm ci
            - name: Validate commits with commitlint
              run: npx commitlint --from ${{ github.event.before }} --to ${{ github.event.after }} --verbose
